baseurl = "https://til.nikovacevic.io/"
languageCode = "en-us"
title = "TIL"
theme = "stark"

[permalinks]
  post = "/:year/:month/:day/:title/"
  page = "/:title/"

[[menu.home]]
  name = "TIL"
  url = "/"

[[menu.left]]
  name = "Niko"
  url = "https://nikovacevic.io/"

[[menu.right]]
  name = "GitHub"
  url = "https://github.com/nikovacevic"
[[menu.right]]
  name = "StackOverflow"
  url = "https://stackoverflow.com/users/4320971/niko-kovacevic"
[[menu.right]]
  name = "Strava"
  url = "https://strava.com/athletes/6476954"
[[menu.right]]
  name = "Twitter"
  url = "https://twitter.com/NikoKovacevic"
