baseurl = "https://til.nikovacevic.io/"
languageCode = "en-us"
title = "TIL / Niko Kovacevic"
theme = "hugo-lithium"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/nikovacevic"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/NikoKovacevic"

[[menu.title]]
    name = "RUN"
    url = "https://run.nikovacevic.io"

[params]
    description = "Niko Kovacevic"

    [params.logo]
    url = "niko.png"
    width = 50
    height = 50
